### ISSUE TITLE
Overwrite Reactables.jsx?

### ISSUE THREAD

**Issue by helloroad** [GigaTables/reactables#102]
Hi, 
in Reactables.jsx is the width hardcoded?

`<div className={styles.gt_container} style={{width: "1128px"}}>`

How can I pass the new width without overwriting the whole class?
Is there any way to pass the value in the <Reactables/> level?

Thanks

**Comment by arthurkushman** [comment]
It would be a good idea to pass the width via `settings` as u may thing in the 1st place, but if u think of that in terms of UX you can see that there are difficulties in how to manage different width with adjustment of different columns, how to scale up/down them for different devices etc, do u have additional thoughts or probably solution for these problems chaining each other?

**Comment by arthurkushman** [comment]
There will be the minimum columns length summed for ex.: if min columns width will be 800px and in settings 650px, the table width will get 800px, but the upper bound can be modified dynamically via settings.

**Comment by helloroad** [comment]
I see. Thanks for the reply

**Comment by arthurkushman** [comment]
Patch has been released - https://github.com/GigaTables/reactables/releases/tag/2.3.13
