### ISSUE TITLE
data doesn't get updated in GT after editing

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#106]
I think the reason lies in line 442-445 of Editor.js, where dataResp doesn't update its values according to the received data. The data in the dababase do get updated.

442            }).then(response => response.json()).then((data) => {
443                editorUpdate(e, dataResp);
444                this.triggerAfter(EditorConstants.EDITOR_EDIT);
445            });

**Comment by arthurkushman** [comment]
Hi
- How many rows you've been updated?
- Have u sorted or searched data before edited?

**Comment by wangfrombupt** [comment]
1. only one row is updated;
2. default sort and no search conditions.

**Comment by wangfrombupt** [comment]
Yes, I send back the updated row from back-end because there is a generated column (just like the case in the row creating) in it. Simply returning an empty json would not make the row filled with newly generated column value.

**Comment by arthurkushman** [comment]
Can u post an example of response data here, then I can test with it?

**Comment by arthurkushman** [comment]
I've tested edit behavior in different situations, weather it is an empty object or an array like this:
```
{
    "rows": [
        {
            "GT_RowId": 1,
            "id": 1,
            "title": "Test 1021st row sdfvsdfvdf",
            "desc": "<p>vsdfvdsfvsdf<br>\nvsdfvsdf<br>\nvsdfv<\/p>",
            "date": "2018-05-04"
        }
    ]
}
``` 
everything works fine, so I'm waiting for your example of output data.

**Comment by Thomstrong** [comment]
I've tried the following three testing data on release 2.4.3, none of them works:

{"rows":[{"id":482,"gk":"12312","year":2018,"gkhwttl":3213,"metric":1,"GT_RowId":482}]}

{"rows":[{"id":482,"gk":"12312","year":2018,"gkhwttl":3213,"metric":1}]}

{"rows":{"id":482,"gk":"12312","year":2018,"gkhwttl":3213,"metric":1}}

**Comment by Thomstrong** [comment]
A further debuging of the corresponding code of Editor.js shows that the variable dataResp does contain the updated values, but the content of the GT would not get updated after closing the pop-up window by clicking the "update" button. Only when I click the reload button of the browser, does the content of GT refreshed to show the new value of the edited record.

BTW, I'm a student of wangfrombupt. I like gigatable very much and hope to be helpful for improving it.
Looking forward your feedback, thanks.

**Comment by arthurkushman** [comment]
Ok, I've tried all possible formats from these are perfect fit:
```
{"rows":[{"id":482,"gk":"12312","year":2018,"gkhwttl":3213,"metric":1,"GT_RowId":482}]}

{"rows":[{"id":482,"gk":"12312","year":2018,"gkhwttl":3213,"metric":1}]}
```
no errors, warning or not working functionality (by editing rows) found, also tested with multiple rows - works as expected.
Suppose there may be problems with GT settings, could u provide settings and editor json here from main.js, it would be better to copy/paste all content from main.js file, or wherever all settings for GT is, with JSX, thus I can debug the issue, what browser are using? version? also will be helpful.

**Comment by Thomstrong** [comment]
3. about browser
We use Chrome 66.0.3359.139 （64bit）on Windows 10 (64bit) to carry out the test.

**Comment by Thomstrong** [comment]
I have a new finding!
I try to modify the variable "editeableCells"  of GT setting  to "true", and the record will change after update button clicked.But when I click the field I have changed just now, the value will be go back to the old one right away

**Comment by arthurkushman** [comment]
Thx a lot, as soon as I find time - try to fix this.

**Comment by arthurkushman** [comment]
Fixed by adding children prop check to Column component, this was serious glitch which could produce unexpected behavior. Patch release -  https://github.com/GigaTables/reactables/releases/tag/2.4.4

Editable cells also fixed, if you send back an object like:
```json
{
    "rows": [
        {
            "desc": "Foo bar baz",
            "id": 968
        }
    ]
}
```
cell will be properly edited. Thx.

**Comment by Thomstrong** [comment]
Now the content of GT can reflect the new values of editor fields, but the generated column value is not updated. It is the same issue as [#98](https://github.com/GigaTables/reactables/issues/98). Please fix it as well.

**Comment by arthurkushman** [comment]
Thank u - I've opened issue #108 for better history and closing this.
