### ISSUE TITLE
add a customizable button

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#111]
Can you add a customizable button for GT, so that the button's function can be specified by GT users through setting its parameters such as URL, HTTP method? 
The current buttons (i.e. create, delete, update and reload buttons) has built-in functions and not suitable for serving other app-specific functions.
In my case, I need GT have a button to inform the backend to recreated the corresponding database table before returning the table's content.
I've tried to use reload button to implement this function with no luck. Since reload button doesn't allow to specify its own URL (it uses the default URL specified in GT settings)  and its triggerBefore function doesn't wait for the completion of the requested backend operation (In triggerBefore we use the asynchronous fetch call to request backend operation ), the GT table gets reloaded immediately with the default URL which requests the old data.

**Comment by arthurkushman** [comment]
Could u provide some examples of JS tables with customizable buttons, especially with url/uri? 
It would be interesting to see other implementations.
