### ISSUE TITLE
table display incorrectly after clicking the last page number at the bottom

### ISSUE THREAD

**Issue by xuanxiaodeyu** [GigaTables/reactables#123]

**Comment by arthurkushman** [comment]
Hi, may I ask u a few questions? 
- incorrectly how in particular?
- in what browser?
- what the amount of pages?
- how many entities it renders?
- do u have screen-shots of that behavior?

**Comment by xuanxiaodeyu** [comment]
this is the right page:
http://p7wkolhom.bkt.clouddn.com/other/1.png
After I click the page 3, the data on the page 3 isn't displayed:
http://p7wkolhom.bkt.clouddn.com/other/2.png
the browser is google chrome.

**Comment by arthurkushman** [comment]
Are there >=101 rows in data?

**Comment by xuanxiaodeyu** [comment]
Yes, there are 103 rows. The button 3 at the top of the page work properly but the button at the bottom doesn't. No data is displayed after clicking the page 3 button.

**Comment by arthurkushman** [comment]
I've set 103 rows and `pagination: ['bottom', 'top']` - works perfect with sorting and clicking on 3 page at the top and bottom. Could you post settings or video somewhere to see what happens in your case?

**Comment by xuanxiaodeyu** [comment]
this is my settings:
```
let settings = {
    struct: {
        search: ['top', 'bottom'],
        rowsSelector: ['asc', 'top', 'bottom'],
        pagination: ['top', 'bottom'],
        fixedHeader: true, // default false
        editableCells: false, // default false
    },
    lang: 'ch', // english default
    perPageRows: [25, 50, 100, 200, 500],
    defaultPerPage: 50,
    ajax: '/get_table_jxztpj',
    requestType: 'GET',
    columns: [
        {
            data: "year",
            sortable: true,
            searchable: true
        },
...
```
This video will show my problem to you:
https://youtu.be/okuPsstVorA

**Comment by arthurkushman** [comment]
I've tested with exactly the same amount of rows and settings, e.g. `fixedHeader: true` etc, also tried ch lang.
You can see results here:
https://www.youtube.com/watch?v=68q5zjC_lxg&feature=youtu.be
