### ISSUE TITLE
can't edit the data that aren't on the first page

### ISSUE THREAD

**Issue by xuanxiaodeyu** [GigaTables/reactables#126]
My gigatable has three pages and the data on the first page can be edited, but when I switch to the second page or the third page, the data selected can't be edited, instead, the data on the first page will be edited.
For example, I select the first row on the second page and click the edit-button, the data shown in the edit box is the first row on the first page. And when I edit, the data on the first page is changed but the data on the second page isn't.
Can you help me fix this bug?

**Comment by arthurkushman** [comment]
Sure, what happens after table reload - is data edited or not?

**Comment by xuanxiaodeyu** [comment]
I want to edit the data on the second page, but when I select one row on the second page and click the edit-button, the data shown in the edit-box is not the row that I want to edit, it's the corresponding row on the first page.
After I edit the data, the row on the second page is not changed, but the corresponding row on the first page is changed.
Do I make myself clear? I can record a video if you need.

**Comment by arthurkushman** [comment]
No movies, no worries =)

**Comment by arthurkushman** [comment]
https://github.com/GigaTables/reactables/releases/tag/2.7.7

here is a patch with fix, if u have time and a wish it would be great to test the same bug with search and select on > 1 page.

**Comment by xuanxiaodeyu** [comment]
I tried this version but found that the two bugs still exist.
Now all rows either on the first page or other page can't be edited. When I select one row and click the edit-button, nothing is displayed. I find some errors in the console:
![image](https://user-images.githubusercontent.com/31496912/45868557-a71b0c80-bdb8-11e8-9605-68c474747da4.png)
However, after searching keywords I can edit the rows, but just like before, the data changed isn't dispalyed even though it is realy changed on the database.

**Comment by arthurkushman** [comment]
Ok, I'll back to this issue as soon as I can find free time, thank u for reply.

**Comment by arthurkushman** [comment]
https://github.com/GigaTables/reactables/releases/tag/2.7.8

Now any selected rows should be edited fine, data returned from back-end must be reflexive.

**Comment by xuanxiaodeyu** [comment]
The first bug is still not fixed that when I select one row and click the edit-button, the whole page shows nothing. And the same errors are reported in the console.
Another bug is changed. after searching keywords I can edit the row and the changed data are shown. But if more than one rows  are displayed after searching, then select one of them and edit it, all rows displayed will change to show the edited data.

**Comment by arthurkushman** [comment]
Are u sure the data returned from back-end is correspond to this format:
```
{
    "rows": [
        {
            "GT_RowId": 9001,
            "id": 9001,
            "title": "Test 9001st row CHANGED COLUMN",
            "desc": "<p>CHANGED COLUMN<\/p>",
            "date": "16:16:29 22:09:2018"
        }
    ]
}
```
thus, even if u have 1 row it should be returned in a `list` which key is strictly - `rows`? Also id or GT_RowId must be returned, it couldn't be parsed otherwise.

If there any issues further, please provide more accurate info copy and paste errors, logs, returned values etc.
Thx.

**Comment by xuanxiaodeyu** [comment]
Sorry, there is only id in the returned data. What is GT_RowId? Do I need to set a field named 'GT_RowId' in the returned data? If I do, what is the requirement for this field?

**Comment by arthurkushman** [comment]
`GT_RowId` field used for internal purposes, some time ago u could set only id, but at this time I see issues when this field is not set. So, yes u should set it if u want gt work properly. I'll create another issue to fix this behavior, because it requires more time to debug every component.

**Comment by arthurkushman** [comment]
Is it ok with `GT_RowId`, it should be, I've been tested.
