### ISSUE TITLE
Example Gigatables

### ISSUE THREAD

**Issue by KatiuscaH** [GigaTables/reactables#129]
Hello, I'm newbie with react and I need to display data in a table and make CRUD. I have an API with this functionalities, but I don't know how to implement GigaTables in my code. Can I see any example code or something to guide me? Thanks a lot

**Comment by arthurkushman** [comment]
See here- https://github.com/GigaTables/reactables#user-content-minimal-configuration
Of course u'll need to install npm and all dependencies for Gigatables, but it is simple as run:
```
brew install node
```
and
```
npm i
```
google everything u don't know.
