### ISSUE TITLE
Minimal Configuration error

### ISSUE THREAD

**Issue by chppppp** [GigaTables/reactables#142]
I am a newb to React so forgive me :) 

I have a base project using this tutorial: https://reactjs.org/tutorial/tutorial.html

I am trying to display the default Minimal Configuration table on my page. I have added all the relevant config, including the webpack.config.js in my root dir. When I `npm start` the webserver boots but my page gives me an error: `Error: Target container is not a DOM element.`

Any help/advice is appreciated. Thank you!

**Comment by chppppp** [comment]
Ooops - I did not add the appropriate code to `index.html`. After doing so I get a new error

```
Error: Element ref was specified as a string (tableLoaded) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.
```

**Comment by arthurkushman** [comment]
Hello thanks for issue, I'll definitely take a look at this problem later probably at week-end.
It seems like deprecated features in ReactJS.

**Comment by chppppp** [comment]
Thanks Arthur! I was thinking it could be webpack related as well, the webpack.config.js references a main.js but in my project im using index.js. 

I am a newb to React so I am still figuring out all the little pieces :)

**Comment by chppppp** [comment]
Would it be possible for you to provide a basic example project that uses Gigatables for nubs like me?

**Comment by chppppp** [comment]
So I think my issue was with webpack... I just cant get any data now using https://jsonplaceholder.typicode.com/todos for testing. My table just says `Loading...`

**Comment by arthurkushman** [comment]
Now I see - u don't have required `rows` key in the document, so it should look like that:
```
{ "rows": [
  {
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
  },
.....
]
}
```

**Comment by chppppp** [comment]
Thank you!!!

**Comment by chppppp** [comment]
Is there a way to change the "rows" part to accept different formatted json feeds?

**Comment by arthurkushman** [comment]
For example?

**Comment by chppppp** [comment]
I have a flask backend that is just doing a lazy `jsonify` on `/var/log/syslog/' on an Ubuntu box.
From the raw data it looks like It's just returning a list:
```
[
  "Oct 30 00:07:40 frickyou anacron[23035]: Job `cron.daily' terminated\n", 
  "Oct 30 00:07:40 frickyou anacron[23035]: Normal exit (1 job run)\n", 
  "Oct 30 00:12:05 frickyou systemd[1]: Starting Daily apt download activities...\n", 
  [...]
]
```

I guess the better question is - how do i modify what the package is expecting?

**Comment by chppppp** [comment]
I created an API that follows the spec:

```
{
  "rows": [
    {
      "date": "Oct 30 ", 
      "hostname": "frickyou", 
      "msg": "anacron[23035]: Job `cron.daily' terminated", 
      "time": "00:07:40"
    }, 
    {
      "date": "Oct 30 ", 
      "hostname": "frickyou", 
      "msg": "anacron[23035]: Normal exit (1 job run)", 
      "time": "00:07:40"
    }, 
```

I modified my code to match the dictionary keys. I no longer get `Loading...` but I get no data now.

**Comment by chppppp** [comment]
I have a network error in my console logs but the api works fine from my browser... when this makes the ajax call, does the server or the browser make that call?

**Comment by chppppp** [comment]
apparently the `id` key is required in the json results :)

**Comment by arthurkushman** [comment]
`rows` must be anyway, but the inner structure is free to change in any way:
```
{ "rows": [
  {
   {"log":"Oct 30 00:07:40 frickyou anacron[23035]: Job `cron.daily' terminated\n"}, 
   {"log":"Oct 30 00:07:40 frickyou anacron[23035]: Normal exit (1 job run)\n"}, 
  },
.....
]
}
```
so there will be 1 column log, you can put as many columns as u wish and those which shouldn't be displayed will be empty. 
PS imagine this as rows/columns - nothing more nothing less.

**Comment by arthurkushman** [comment]
> apparently the `id` key is required in the json results :)

Yes, if you didn't set GTRow_id, then the id will be taken for data manipulation.
