### ISSUE TITLE
Not an issue - Just help needed

### ISSUE THREAD

**Issue by tayzee** [GigaTables/reactables#41]
Hi,

I am trying to test your tables in my react project as your component is the closest to my requirement.

I cant for the life of me get it to work though, here is my code below, maybe you can tell me if im doing something wrong. Im a newbie with react, so this could be adding to the problem but Ive tried for many hours, so please bare with me.

I have populated the test.php file with the same code from your php file and when i run it in my terminal it renders the results.

When I run this my main container div in the app is rendering nothing, not even the card.

import React from 'react';
import { Reactables, Header, editor } from 'gigatables-react';
import { Card, CardTitle} from 'reactstrap';

var settings = {
 struct: {
   search: ['top', 'bottom'],
   rowsSelector: ['desc', 'top', 'bottom'],
   pagination: ['bottom']
 },
 lang: 'en', // english default
 perPageRows: [25, 50, 100, 200],
 defaultPerPage: 100,
 ajax: 'test.php',
 // ajaxAutoloadData: true, // default false
 // ajaxAutoloadPeriod: 8, // sec
 requestType: 'GET',
 columns: [
   {// include all defaults
     data: "id",
     sortable: true, // true by defualt
     visible: true, // true by defualt
     searchable: true, // true by defualt
     discreteSearch: true, // false by default
     discreteSearchValue: function (title) {
       return 'Search by field - ' + title;
     }
   },
   {
     data: "title",
     cISearch: true // default false
   },
   {
     data: "desc",
     sortable: false,
     discreteSearch: true,
     discreteCISearch: true // default false
   },
   {
     data: "date",
     searchable: false
   },
   {
     data: "info"
   },
   {data:"field1"},
   {data:"field2"},
   {data:"field3", visible: false}
 ],
 columnOpts: [
   {
     render: (data, row, type) => (
       <div>
         <form method="post" action="">
          <input type="hidden" name="action" value="forms" />
          <input type="hidden" name="id" value={row.id} />
          <div>{data}</div>
        </form>
      </div>),
     target: 'title' // provide data column index to match opts
   },
   {
     render: (data, row, type) => (
        <div>
          <div>{data}</div>
          <div>{(row.id % 2 === 0) ? '**' : '*'}</div>
        </div>
       ),
     target: 'date'
   }
 ],
 tableOpts: {
   buttons: [
     {extended: "editor_create", editor: editor, triggerAfter: (function () {
         console.log('after create');
       }), triggerBefore: (function () {
         console.log('before create');
       })},
     {extended: "editor_edit", editor: editor, triggerBefore: (function () {
       console.log('before edit');
     })},
     {extended: "editor_remove", editor: editor, triggerAfter: (function () {
         console.log('after del');
       })}
   ],
   buttonsPosition: ['top', 'bottom'],
   theme: 'std'
 }
};

export default class UserManPage extends React.Component {

  render() {
    return (

      <div>
        <Card block>
          <CardTitle>My Table</CardTitle>
            <Reactables editor={editor} settings={settings}>
              <Header data="id">ID</Header>
              <Header data="title">Name</Header>
              <Header data="desc">Description</Header>
              <Header data="date">Date</Header>
              <Header data="info">Info</Header>
              <Header data="field2">Field123 but data from field2</Header>
              <Header data="field1">Field1</Header>
              <Header data="field3">Field3 invisible</Header>
              <Header>Field3 invisible</Header>
            </Reactables>
        </Card>
      </div>
    );
  }
}

**Comment by arthurkushman** [comment]
Hi, first of all - the import should be declared like this:
```js
import { Reactables, Header } from 'gigatables-react'
```
there is no component/class like `editor`. There are Editor class, which is used internally.

Another thing that I can see - You hadn't declared `var editor = {}` object to provide it in settings

```js
{extended: "editor_edit", editor: editor, triggerBefore: (function () {
console.log('before edit');
})},
```

Read about it here https://github.com/GigaTables/reactables#user-content-an-example-of-using-gigatables-with-editor-tool  - it should be declared before `var settings` object.

Also, may be U can see errors in React Developer Tools? Probably some warnings?

**Comment by tayzee** [comment]
Great, thanks for that.

I have managed to make it work.

I just need two more answers from you if possible.
1) Are the tables not responsive?
2) Is it possible to fix the header and have the table data scrolling below?

Thanks

**Comment by arthurkushman** [comment]
Glad that answer was helpful.
1. If this question means ex.: horizontal/vertical scrolling while shrink the browser window - no.
2. Not yet, but thoughts about an integration of this kinda functionality visited me and I think that it is rather be implemented for better UX in near future.

**Comment by arthurkushman** [comment]
I`m closing this discussion with functionality for fixed header https://github.com/GigaTables/reactables/releases/tag/1.6.1
It is already build + published, so enjoy =)
