### ISSUE TITLE
Unable to render Reactables

### ISSUE THREAD

**Issue by gc-alexlong** [GigaTables/reactables#46]
Hello! I am implementing a table without editor settings for a React app I'm creating, as I don't need the editor portion. I get error `Uncaught TypeError: Cannot read property 'fields' of undefined` when the component attempts to load in browser.  In Firefox, I see `TypeError: t is undefined`, but I don't know if that's a separate issue.

React Version: 15.5.4

**Comment by arthurkushman** [comment]
Hi, here is a patch with fix - https://github.com/GigaTables/reactables/releases/tag/1.6.2
You can just exclude an `editor` prop from `<Reactables>`.
Also, don't forget to delete buttons from `tableOpts` in settings prop, if You did so.

**Comment by gc-alexlong** [comment]
Hello,

The issue still persists after patching, but now the error is a bit different, `Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at t.value (index.js:27)`

**Comment by arthurkushman** [comment]
Ok then, can You please post code snippet, of table definition with options/props?
thx for contribution

**Comment by arthurkushman** [comment]
Another patch, tested with "Minimal configuration" - https://github.com/GigaTables/reactables/releases/tag/1.6.3
