### ISSUE TITLE
Errors not going through DataException

### ISSUE THREAD

**Issue by AndreiEnache** [GigaTables/reactables#52]
I had a problem because my json didn't contain a 'rows' property but couldn't diagnose it because the error was 

` Uncaught (in promise) TypeError: Cannot set property 'message' of undefined `

This can be fixed by re-writing the exceptions like this
` const DataException = function(message) {
   this.message = message;
   this.name = "DataException";
 };
 const EditorException = function(message) {
   this.message = message;
   this.name = "EditorException";
 };`

**Comment by arthurkushman** [comment]
Hi, this error probably accruing because of uninstalled/non-configured `es` presets like in project's webpack cnofig ex.:
```js
   module: {
      loaders: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
               presets: ['es2015', 'react']
            }
         },
```
so this is rather es6 issue, where arrow functions were introduced.

**Comment by AndreiEnache** [comment]
I have those exact configured presets. Also used the npm package which uses a pre-compiled version of the files. But if the errors work for you it might be an issue on my side. As far as I know arrow functions don't rebind 'this' which makes the this.message undefined

**Comment by arthurkushman** [comment]
Thx for contribution and actual pull request, I've analyzed the problem - you were right.
