### ISSUE TITLE
Editor is not working

### ISSUE THREAD

**Issue by shyam2027** [GigaTables/reactables#54]
I hosted editor.php & UploadFiles.php  in xampp which i took from another version(https://github.com/GigaTables/gigatables)
while i edit or delete anything it throws following error
index.js:17058 Fetch complete: PUT "http://localhost/editor.php".
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
Please help me on these 
Thanks in advance how ill resolve this

**Comment by arthurkushman** [comment]
U shouldn't use those files from another project because the semantic of requests was changed with PUT/DELETE etc e.x.: You can't accept parameter via global $_POST variable for PUT. 
You should use something like 
```php
  if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $params = json_decode(filter_var_array($_POST), true);
    $data['row'] = [
        'GT_RowId' => 12314,
        'id' => 12314,
        'title' => $params['title'],
        'desc' => $params['desc'],
        'date' => $params['date'],
            ];

  }

  if ($_SERVER['REQUEST_METHOD'] === 'PUT') {
    $params = json_decode(file_get_contents('php://input'), true);
    $data['row'] = [
        'GT_RowId' => $params['id'],
        'id' => $params['id'],
        'title' => $params['title'],
        'desc' => $params['desc'],
        'date' => $params['date'],
            ];
  }

  if ($_SERVER['REQUEST_METHOD'] === 'DELETE') {
    $data['row'] = json_decode(file_get_contents('php://input'), true);
  }

  echo json_encode($data, JSON_PRETTY_PRINT | JSON_NUMERIC_CHECK | JSON_UNESCAPED_UNICODE);
```

PS Anyway the code on back-end is Your own program, You should provide the compatible JSON output for plug-in.

**Comment by shyam2027** [comment]
Shall i put this in editor.php

**Comment by arthurkushman** [comment]
U should code it Your-self, it is free implementation unrelated to Gigatables written on JS - it's just an example, You can place it in any file and set url like this: 
```
var editor = {
  ajax: 'http://example.com/WHATEVER.php',
```

**Comment by shyam2027** [comment]
Thanks Thanks alot dude :-) Thanks its helped alot :-)

**Comment by arthurkushman** [comment]
U R welcome, by the way U can always appreciate me with starring this project =)
