### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by cesoftinfo** [GigaTables/reactables#57]
Looking great but I have problem making it work, can you provide working example?

**Comment by arthurkushman** [comment]
Hi, here it is:
https://github.com/GigaTables/reactables/blob/master/main.js

Did u install all the node modules or have placed it as a script on your page? 
Provide all the information about installing process that U've been made.

**Comment by cesoftinfo** [comment]
Hi, thanks for quick response...
I have error in console : 
 Failed to load resource: gigatables.loc/gigatables.php net::ERR_NAME_NOT_RESOLVED

**Comment by arthurkushman** [comment]
Sure, there should be your back-end that provides data for grid-rendering. Ex.: http://mycompany.com/grid/output/etc See json format need to be provided in readme.

**Comment by cesoftinfo** [comment]
OK, I installed json server locally and now it work's. I must say it is awesome, is it possible to load table data from state or must be externally?

**Comment by arthurkushman** [comment]
Data must be uploaded externally. If u really liked the plug-in I would be grateful if u press the "star" button.
