### ISSUE TITLE
Editor validation fileds

### ISSUE THREAD

**Issue by cesoftinfo** [GigaTables/reactables#58]
How would be propper way to add validation to editor fields?

**Comment by arthurkushman** [comment]
Hi, there are few options:
- html way you can use attributes like type, pattern etc, there are examples in readme
- you can use one of triggers, as described in FAQ - Does GT have any event-triggered functions, ex.: to run something before/after pop-up?
GigaTables plug-in has 2 types of triggers triggerBefore and triggerAfter which can be applied to any action button - Create, Edit or Delete.

There U can define any JS handler to prevent user of entering wrong data.

**Comment by cesoftinfo** [comment]
OK, but how to render error messages in editor dialog?

**Comment by arthurkushman** [comment]
You can easily run the script in triggerAfter function and place the results in 
```html
<div class="gte_footer"><div class="gte_form_err"></div>...
```

**Comment by cesoftinfo** [comment]
Now I get error Uncaught TypeError: Cannot read property 'files' of undefined
    at Editor.fileUpload even though i dont have file upload field.

**Comment by arthurkushman** [comment]
Can't predict what u've done - post your code here with settings and editor jsons, pls.

**Comment by arthurkushman** [comment]
In before create u don't need to return anything, just use something like 
```
document.querySelector('div.gte_editor div.gte_form_err').innerHTML = 'some error occurred';
```

**Comment by cesoftinfo** [comment]
Again same error realted to fileUpload:
 Uncaught TypeError: Cannot read property 'files' of undefined
    at Editor.fileUpload (index.js:19379)
    at Editor.btnClicked (index.js:19636)
    at HTMLUnknownElement.boundFunc (index.js:9781)
    at Object.ReactErrorUtils.invokeGuardedCallback (index.js:9787)
    at executeDispatch (index.js:9319)
    at Object.executeDispatchesInOrder (index.js:9339)
    at executeDispatchesAndRelease (index.js:5963)
    at executeDispatchesAndReleaseTopLevel (index.js:5974)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (index.js:14703)

**Comment by arthurkushman** [comment]
It is nothing to do with structures in your code, but with json-data which should be something like:
```json
{"rows":[{"GT_RowId":186,"title":"Test Foo 186st row","id":186,"desc":"Lorem Ipsum is simply dummy Foo 5159 text of the printing and typesetting","info":"some info some info some info some info","date":"22:56:46 12:10:2017","field1":0,"field2":1420,"field3":12531},{"GT_RowId":33,"title":"Test Bar 33st row","id":33,"desc":"Lorem Ipsum is simply dummy Bar 4236 text of the printing and typesetting","info":"some info some info some info some info","date":"22:59:19 12:10:2017","field1":33,"field2":1267,"field3":12378},...
```

Please, for future postings add code in triple apostrophes - there is many info about github over there (ex.: google) how to post code blocks. If there will be any questions about main.js file - post the whole file, because it may be headers, or probably other code between etc. In other words try to be more precise, to make it totally clear for your opponent.
