### ISSUE TITLE
REST environment 

### ISSUE THREAD

**Issue by Markohui** [GigaTables/reactables#79]
Can I specify different URLs for the create, edit and remove actions like in datatables Editor?
 ajax: {
            create: {
                type: 'POST',
                url:  '../php/rest/create.php'
            },
            edit: {
                type: 'PUT',
                url:  '../php/rest/edit.php?id=_id_'
            },
            remove: {
                type: 'DELETE',
                url:  '../php/rest/remove.php?id=_id_'
            }
        }

**Comment by arthurkushman** [comment]
Hi, at this moment it can't be done, but this is a great idea to implement such functionality. 
It will definitely help distribute back-end end-points, dependencies etc.

**Comment by arthurkushman** [comment]
Here is a patch - https://github.com/GigaTables/reactables/tree/2.2.1 
U can update via npm.
