### ISSUE TITLE
Unable to deselect the record

### ISSUE THREAD

**Issue by FaizalNoordeen** [GigaTables/reactables#83]
Hi,
 if ctrl + A selected all the records if i want to deselect only one record is not possible? if possible please guide me on how to do.. thanks in advance and ill star for your effort on giga awesome

**Comment by arthurkushman** [comment]
Sorry, didn’t see the issue for a long time. I’ll be defenitelly work on this feature. While this feature will be developed you can use Shift+arrow up/down and Ctrl+click combinations. Thx for reporting.

**Comment by arthurkushman** [comment]
Set things done.
Released patch 2.3.3 - happy usage.
