### ISSUE TITLE
Allow to take promise or URL in calls to fetch to enable easy override

### ISSUE THREAD

**Issue by MichaelF77** [GigaTables/reactables#84]
Can you please consider replacing:

fetch(this.settings.ajax).then(....)

with

Promise.resolve(this.settings.ajax).then(fetch).then(....)

Allows one to specify a different behavior for getting and posting data using local data for instance while maintaining complete compatibility with exiting code sine resolve('url') resolves immediately to 'url'

**Comment by arthurkushman** [comment]
Hi, thank you for contribution.
I've made some experiments and found out that `Promise.resolve` returns `PromiseStatus` and the resolved url value (`PromiseValue`), with code:
```js
Promise.resolve(ajaxUrl).then(fetch(ajaxUrl, {
                method: settings.method,
                body: JSON.stringify(dataIndices)
            }).then(response => response.json()).then((data) => {
                dataResp['id'] = data['row']['id'];
                dataResp[CommonConstants.GT_ROW_ID] = data['row']['id'];
                editorUpdate(e, dataResp);
                this.triggerAfter(EditorConstants.EDITOR_CREATE);
            }))
```
The returned Promise value will be:
```js
Promise {<pending>}__proto__: Promisecatch: ƒ catch()arguments: (...)caller: (...)length: 1name: "catch"__proto__: ƒ ()[[Scopes]]: Scopes[0]constructor: ƒ Promise()finally: ƒ finally()arguments: (...)caller: (...)length: 1name: "finally"__proto__: ƒ ()[[Scopes]]: Scopes[0]then: ƒ then()Symbol(Symbol.toStringTag): "Promise"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()[[PromiseStatus]]: "resolved"[[PromiseValue]]: "http://gigatables.loc/editor.php"

```
which seems more reliable then standard Promise from fetch method - [[PromiseValue]]: undefined.

The question is - how would you use this feature, as the code doesn't return anything? 
The only way to see the Promise result is via debugger.
Can you please post an example of usage or provide more detailed information?

**Comment by MichaelF77** [comment]
Here is how I am using it with the modification I described:

function getUrl() {
	return new Promise( (resolve) => {
		someExternalNonRestAPI.getData()
		.then( (apiResult) => {
			var data = {"rows":[]};
			for (var i = 0;i<apiResult.data.length;i++) {
			 var r = apiResult.data[i];
			 r["GT_RowId"]=i;
			 data.rows.push(r);
		    }
                  var url = URL.createObjectURL(new Blob([JSON.stringify(data)], { type: 'application/json' }));
		  resolve(url)
		  })
	})


and then in the settings:

...
ajax: getUrl()
}

**Comment by arthurkushman** [comment]
Now I see the point and will recode function to test if it is a Promise object to accept url from it.
Thx

**Comment by arthurkushman** [comment]
Use the https://www.npmjs.com/package/valid-url lib for ReactJS to validate url before passing it to fetch function.

**Comment by MichaelF77** [comment]
Validating URL is not the problem, the issue is that a the moment component expects string and so it gets called right away, I need async (Promise) so the data is returned when ready.

**Comment by arthurkushman** [comment]
No offense, this is just a memo for myself to implement an additional functionality. There will be a Promise object to accept url from another Promise, as mentioned previously.

PS by the way, why don't you propose a pull request - it seems like u know what u are doing? =)

**Comment by arthurkushman** [comment]
You can check new algorithm at master, would u mind to add star, so more developers will contribute to this little project?
