### ISSUE TITLE
Force refresh

### ISSUE THREAD

**Issue by MichaelF77** [GigaTables/reactables#85]
Is there a way to force reload from ajax API based on some external event or state, but not automatically.

**Comment by arthurkushman** [comment]
Hi, here is the only way to do that:
```
GigaTables plug-in has 2 types of triggers triggerBefore and triggerAfter which can be applied to any action button - Create, Edit or Delete.
```

**Comment by MichaelF77** [comment]
I figured out how to force refresh using following snippet:
`    reloadGrid() {
		loadData()
		.then( (data) => {
                let jsonData = data['rows'] ? data['rows'] : data['row']; // one row or several
                this.reviewGrid.jsonData = jsonData;
                this.reviewGrid.createTable(jsonData);
                this.reviewGrid.setTableSort();
		  })
	}
`

Thanks for great work !
