### ISSUE TITLE
Creating a global .active class conflicts with React Router's NavLink active class

### ISSUE THREAD

**Issue by pak11273** [GigaTables/reactables#87]
Is there a reason why .active was made !important and global in the css styles?  Anywhere I use React Router's NavLink I cannot use the active style functionality.

**Comment by arthurkushman** [comment]
Another patch - https://github.com/GigaTables/reactables/releases/tag/2.3.6
Would you mind to press star button to support this project?
Anyway, thank u for contributing.

**Comment by pak11273** [comment]
I'd love to star this project but it's too buggy on my end.  I'm still getting the csv errors from the last issue I raised(which you closed already) and I'm spending too much time trying to debug it.  I may try this again in the future when it's a little more stable. Thanks for addressing my issues in such a timely manner.  I hope it gains momentum.

**Comment by arthurkushman** [comment]
Wait, let's start proving our conversation, as I don't see any reason to blame the plug-in/lib because, I've put the same code from your snippet and there aren't any errors/exceptions about CSV and other issues, my proof is:
![screenshot from 2018-02-12 22-02-47](https://user-images.githubusercontent.com/2669610/36114631-9693e47e-1041-11e8-8cb3-284273034c6e.png)
![screenshot from 2018-02-12 22-06-05](https://user-images.githubusercontent.com/2669610/36114632-96b11b3e-1041-11e8-836e-2770cf690d33.png)
You can see the version - gigatables-react@2.3.6
And there is simple table without extra settings, but sorting. Just before releasing, I've tested the CSV button and settings discretely - there were no errors. 
Your turn? (with proof this time please)

**Comment by pak11273** [comment]
hmm.  I removed all of the code I created to test your plugin.  But since you've responded I'll reconstruct it and post results soon.  Thanks for responding!

**Comment by pak11273** [comment]
I'm using:
"react": "15.6.1",
"webpack": "3.0.0",
"gigatables-react": "2.3.6"  //updated to latest version

````javascript
// frontend
// localhost:8080/gigatables
import React, {Component} from 'react'
import {Reactables, Header} from 'gigatables-react'

class Gigatables extends Component {
  constructor() {
    super()
  }
  render() {
    var settings = {
      struct: {
        // all in
        download: {
          csv: false
        },
        search: ['top', 'bottom'],
        rowsSelector: ['asc', 'top', 'bottom'],
        pagination: ['bottom']
      },
      ajax: 'http://192.168.68.8:3001/gigatables',
      columns: [
        {data: 'id'},
        {data: 'desc'},
        {data: 'title'},
        {data: 'date'},
        {data: 'types'},
        {data: 'info'}
      ]
    }
    return (
      <Reactables settings={settings}>
        <Header data="id">ID</Header>
        <Header data="title">Name</Header>
        <Header data="desc">Description</Header>
        <Header data="date">Date</Header>
        <Header data="info">Info</Header>
        <Header data="field2">Field123 but data from field2</Header>
        <Header data="field1">Field1</Header>
        <Header data="field3">Field3 invisible</Header>
        <Header>Field3 invisible</Header>
      </Reactables>
    )
  }
}

export default Gigatables

// backend 
// 192.168.68.8:3001/gigatables
// test url
app.get('/gigatables', function(req, res, next) {
  res.json({
    rows: [
      {
        GT_RowId: 2, // optional
        id: 2, // if there is no GT_RowId - try to fetch "id"
        title: 'Test 2st row',
        desc:
          '<input type="text" name="ttl" value="Test 2nd row Test 2nd row Test 2nd row Test 2st row Test 2st row" /> ',
        date: '20:40:37 17:06:2015',
        info: 'some info some info some info some info'
      },
      {
        GT_RowId: 1,
        id: 1,
        title: 'Test 1st row',
        desc:
          '<input type="text" name="ttl" value="Test 1st row Test 1st row Test 1st row Test 1st row Test 1st row" /> ',
        date: '20:40:38 17:06:2015',
        info: 'some info some info some info some info'
      }
    ]
  })
})
````

Never had a problem with the webpack build but here's a screenshot:

![webpack](https://user-images.githubusercontent.com/2309184/36132676-13eae250-103e-11e8-809a-904e292574b7.JPG)

So upgrading to the new version I don't get the csv error anymore but here's the browser output:

![browser](https://user-images.githubusercontent.com/2309184/36132745-95fa8534-103e-11e8-8c2e-c45b105da755.JPG)

No errors but the output is just a plain json object.  I'm using the minimal configuration suggested by your readme.   I'm happy that all the errors are cleared but I don't believe the output is what we're expecting.  If you need to see any other code I can post more.  I'll leave this on my machine for now and I will revisit this again when I get time.

**Comment by arthurkushman** [comment]
So, there is a problem rather with uri route, as u send the GET request to:
```js
app.get('/gigatables', function(req, res, next) {
  res.json({
    rows: [
```
and your web-server responded with this json.
There is nothing about gigatables-react, you should run the hole application where your main render() method exist and embed the code and settings for GT there.

**Comment by pak11273** [comment]
I had conflicting issues with webpack-dev-server and backend but now I get the UI we're expecting.  

![test](https://user-images.githubusercontent.com/2309184/36164007-ac1286c4-10b0-11e8-86bc-bcaab6def55b.JPG)

This is much better, but the current issue belongs to the plugin.

**Comment by pak11273** [comment]
I did some research and I think the issue is probably because your plugin is using react 16.x while I am still using 15.x.  This is a major release and so I am waiting for some time before I migrate.  You might downgrade your react version and see if your plugin still works.  If there are errors, you may want to write up a migration doc.  I will revisit this plugin when I have migrated to React 16.x.  

Side Note: I've been using chrome incognito because the plugin doesn't function correctly with React Developer Tool Extension.  Do you use this extension?
