### ISSUE TITLE
bug: edit a record after filtering shows another record.

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#90]
It seems that GT doesn't handle row id properly after the records are filtered by texts in the search box. When I filter out some records and want to edit one of them(say the 3rd one), the Editor always shows another record which is the 3rd one in the unfiltered record list. Please fix this bug or tell me if I didn't use GT in the correct way.

**Comment by arthurkushman** [comment]
Thank u for report of this kinda unacceptable bug, here is a patch - https://github.com/GigaTables/reactables/releases/tag/2.3.7

**Comment by wangfrombupt** [comment]
Thanks for the rapid fix. It works fine:)
