### ISSUE TITLE
bug: cannot add record

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#91]
While I'm creating a new record and attempts to save it, GT sends out an HTTP request whose content-type field value is text instead of json. I fixed this bug by replacing the following codes in Editor.js
            fetch(ajaxUrl, {
                method: settings.method,
                body: JSON.stringify(dataIndices)
with 
            fetch(ajaxUrl, {
                method: settings.method,
                body: JSON.stringify(dataIndices),
				headers: {
					'Content-Type': 'application/json'
				}

Can you update the source code by fixing this bug?
By the way, the OK buttion of the Editor windows doesn't show any text when I use set lang to 'ch'.

**Comment by arthurkushman** [comment]
Thx again - sure, the Content-Type header must be set to application/json while sending requests, also I see the empty strings in some buttons on other languages, probably it should be set as English by default. I'll fix these bugs in near future.

**Comment by arthurkushman** [comment]
Patch is ready - https://github.com/GigaTables/reactables/releases/tag/2.3.9
