### ISSUE TITLE
enhancement: need refresh button

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#92]
The create, delete and edit buttons are fine. But I also need a refresh button so that users can update the table without having to hit the refresh button of the browser.  I added a standalone refresh button as a workaround, but that's a temporal solution and made the source code harder to follow. Would you please add the refresh button in the GT source code? Thanks.

**Comment by arthurkushman** [comment]
Here is the functionality that can help u in this matter:
https://github.com/GigaTables/reactables#user-content-ajax-autoload-period
Or are there any other issues that may not fit with this feature?

**Comment by wangfrombupt** [comment]
Thx for the reply, but it doesn't solve my problem. One of my tables is created by a stored procedure of MySQL which may take half a minute to complete.  I expect the user to refresh the table whenever he wants (because the user is the admin and he knows the right time to regenerate the table) and waits for the relatively long response time. But with autoload, there will be lots of unnecessary executions of the stored procedure which harm the performance of both client and server. So I think a refresh button as an option would be nice for some particular scenarios like this and will be helpful for other GT users. Please take this into consideration, thanks.
