### ISSUE TITLE
Enhancement:  precise translation of English strings to Simplified Chinese

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#93]
The following are the ch version of the strings in lang.js, but some of the translations are wrong or improper (I'm a Chinese native speaker and a software programmer).
  'ch': {
      'gte_editor_popupheader_delete': '删除',
      'gte_editor_popupheader_edit': '编辑',
      'gte_editor_popupheader_create': '创建行',
      'gte_editor_sendbtn_create': '',
      'gte_editor_sendbtn_update': '',
      'gte_editor_sendbtn_delete': '',
      'show': '显示',
      'entries': '项目',
      'showing': '显示',
      'to': '至',
      'of': '的',
      'prev': '前',
      'next': '未来',
      'search': '搜索',
      'editor_create': '创造',
      'editor_edit': '编辑',
      'editor_remove': '删除'
  },

The correct translation should be:
  'ch': {
      'gte_editor_popupheader_delete': '删除',
      'gte_editor_popupheader_edit': '修改',
      'gte_editor_popupheader_create': '新增',
      'gte_editor_sendbtn_create': '',
      'gte_editor_sendbtn_update': '',
      'gte_editor_sendbtn_delete': '',
      'show': '显示',
      'entries': '条数据',
      'showing': '显示',
      'to': '至',
      'of': '的',
      'prev': '前一页',
      'next': '后一页',
      'search': '查找',
      'editor_create': '新增',
      'editor_edit': '修改',
      'editor_remove': '删除'
  },

**Comment by arthurkushman** [comment]
Wow, thx - would it be not so hard for you to add translation for:
- 'gte_editor_sendbtn_create': '',
- 'gte_editor_sendbtn_update': '',
- 'gte_editor_sendbtn_delete': '',
the words are:
- Create
- Update
- Delete
so it may help users even more.

**Comment by arthurkushman** [comment]
Fixed - https://github.com/GigaTables/reactables/releases/tag/2.3.8

**Comment by wangfrombupt** [comment]
I found that a word by word translation leads to a very wired sentence which is hard to understand because of the different grammars between English and Chinese language. So, I retranslated them as follows, and now the generated sentence looks like a natural Chinese sentence.

  'ch': {
      'gte_editor_popupheader_delete': '删除',
      'gte_editor_popupheader_edit': '修改',
      'gte_editor_popupheader_create': '新增',
      'gte_editor_sendbtn_create': '新增',
      'gte_editor_sendbtn_update': '修改',
      'gte_editor_sendbtn_delete': '删除',
      'show': '显示',
      'entries': '条数据',
      'showing': '显示第',
      'to': '至',
      'of': '条数据，共',
      'prev': '前一页',
      'next': '后一页',
      'search': '查找',
      'editor_create': '新增',
      'editor_edit': '修改',
      'editor_remove': '删除'
  },

**Comment by wangfrombupt** [comment]
Would you please reopen this issue and update the translation? Thanks a lot:)
