### ISSUE TITLE
some prompts need translation

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#95]
For example,  when the user selects a row and hits the delete button, the alert window shows "Are You sure You wish to delete 1  row(s)?"  which doesn't translate to "您确定要删除1条数据吗？" even if I'v set the lang to 'ch'.

**Comment by arthurkushman** [comment]
It is reasonable, but I'm not sure that we have enough expertize to translate all those messages to all 7 supported languages, at this moment I thought it would be good to keep them in English.

**Comment by wangfrombupt** [comment]
I can help with the Chinese translation if you agree.
I think we can extent the lang.js to include prompts in the seven
supported languages. I can only read English and Chinese, but we can use
English prompts as a placeholder for other 5 languages untill some guys
can help to translate them.
Would that be possible?

**Comment by arthurkushman** [comment]
Great idea, and I can translate English and Russian, so by that we can cover 3 of 7.

**Comment by wangfrombupt** [comment]
Glad to hear your agreement. So please set the prompt as a variable that can be set in lang.js, and we and other guys can provide the appropriate translations.
