### ISSUE TITLE
 fixedHeader doesn't work

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#96]
I want to allow users to adjust table header's width to their needs. But setting fixedHeader to false doesn't help. The table headers' width still would change when dragging the border between headers. And is there a way to show the border lines between headers? In that way, it will be easier to find the border and drag it.
Thanks.

**Comment by arthurkushman** [comment]
Can u please give some examples of what u try to achieve?
fixedHeader=true is activating functionality to fix header while scrolling down/up and setting it to false set header stick above 1st row, it's not about adjusting header columns, if u meant this particular behavior.

**Comment by wangfrombupt** [comment]
Oh, I misunderstand the meaning of fixedHeader. You are right, what I
want is allowing users to adjust the header columns. How can I achieve
this effect? Thanks for your help.
BTW, GT is really a lifesaver. I'm using it in one of my demo whose
development time is very tight. With GT, I can complete the CRUD of ten
tables within two days. That's really a great help.
But there's some minor bugs or missed features in the current version of
GT. It would be an awesome component if the bugs are fixed and some
appealing features are added.
Thanks again for your time and nice work:)

**Comment by arthurkushman** [comment]
Nice to hear that, appreciate all the work u did for this project. I've even placed your nickname in "Contribution gratitude" section in README.md.

**Comment by wangfrombupt** [comment]
Thanks for that. GT helps me a lot in my project. I'm very happy if I can do something for it：）
