### ISSUE TITLE
bug: GT doesn't update after rows are deleted

### ISSUE THREAD

**Issue by wangfrombupt** [GigaTables/reactables#97]
If the user selects a row and delete it, the row in the database does get deleted, but the deleted row is still shown in GT. Only after a refresh operation (by clicking the refresh button of the browser) does the GT's display gets updated and the deleted row is gone. Please fix this bug. Thanks.

**Comment by arthurkushman** [comment]
On the server you getting an array of data e.g.: [2,1]  with request method DELETE where u need to delete those rows from DB (probably soft delete), GT instantly removes those fields from table and if u will reload table it should get all rows, but without [2,1]. Can't reproduce this behavior - rows are deleting right after pressing Delete btn and pop-up had been disappeared normally.  The only reason u see them is GET request with those rows present again.

**Comment by wangfrombupt** [comment]
This behavior can be reproduced in this way: first, filter the rows by setting a search text  in the search box and make sure the rows satisfying the search condition are not the same set of first rows in the original table. For example, if the original rows are a1,a2,a3,b1,b2,b3,c1,c2,c3, the rows after searching are expected to be b1,b2,b3  ; second,  select one of the row, say b1, and delete it. Then you will find b2 is still shown in the table although the corresponding record has been deleted from the database.

After debugging GT step by step, I found that selectedRows in the function editorUpdate record the index of rows in the filtered table instead of the row's rowId.  The former is 0 since the deleted row is in the first position of the filtered table, the later is the id value of the corresponding record( in my case 466). So the following code in main.js will not work correctly: 

 if (dataIndices[dataKey] === rowId) {
                        selectedRows.splice(selectedRows.indexOf(key), 1);
                        this.jsonData.splice(key, 1);
                    }

Thus, I thought the root cause of the bug is in the content of seletedRows which should store rowId instead of row index.

BTW, the following code in Editor.js doesn't take failure deletion into consideration, which may confuse the user when records are not deleted successfully from the database but disappear in the GT table(when this bug is fixed).
            fetch(ajaxUrl, {
                method: settings.method,
                body: JSON.stringify(payload),
                headers: headers,
            }).then(response => response.json()).then((data) => {
                editorUpdate(e, dataResp);
                this.triggerAfter(EditorConstants.EDITOR_EDIT);
            });

**Comment by wangfrombupt** [comment]
This behavior can be reproduced in this way: first, filter the rows by
setting a search text in the search box and make sure the rows
satisfying the search condition are not the same set of first rows in
the original table. For example, if the original rows are
a1,a2,a3,b1,b2,b3,c1,c2,c3, the rows after searching are expected to be
b1,b2,b3 ; second, select one of the row, say b1, and delete it. Then
you will find b2 is still shown in the table although the corresponding
record has been deleted from the database.

After debugging GT step by step, I found that selectedRows in the
function editorUpdate record the index of rows in the filtered table
instead of the row's rowId. The former is 0 since the deleted row is in
the first position of the filtered table, the later is the id value of
the corresponding record( in my case 466). So the following code in
main.js will not work correctly:

if (dataIndices[dataKey] === rowId) {
selectedRows.splice(selectedRows.indexOf(key), 1);
this.jsonData.splice(key, 1);
}

Thus, I thought the root cause of the bug is in the content of
seletedRows which should store rowId instead of row index.

BTW, the following code in Editor.js doesn't take failure deletion into
consideration, which may confuse the user when records are not deleted
successfully from the database but disappear in the GT table(when this
bug is fixed).
fetch(ajaxUrl, {
method: settings.method,
body: JSON.stringify(payload),
headers: headers,
}).then(response => response.json()).then((data) => {
editorUpdate(e, dataResp);
this.triggerAfter(EditorConstants.EDITOR_EDIT);
});

祝 身体健康，工作愉快！
---------------------------------------------
王玉龙 副教授
北京邮电大学网络技术研究院
电子邮件: wyl@bupt.edu.cn
手机: 86-13466534057
通信地址: 北京市海淀区西土城路10号北京邮电大学187信箱
邮政编码: 100876
---------------------------------------------
Yulong Wang
Institute of Network Technology
Beijing University of Posts and Communications
E-Mail: wyl@bupt.edu.cn
Cell Phone: 86-13466534057
Mail Box: 187#, Beijing University of Posts and Telecommunications,No.10
Xi Tu Cheng Rd., Hai Dian District, Beijing, P.R.China
Post Code: 100876

在 2018/4/17 22:48, Arthur Kushman 写道:

**Comment by arthurkushman** [comment]
Related to https://github.com/GigaTables/reactables/issues/100
and - https://github.com/GigaTables/reactables/issues/99
Problems solved.
